<?php include 'config.php' ?>
<?php
session_start();
$conn = $mysqli;

$email = strip_tags($_POST['email']);
$generatedPassword = md5($_POST['generatedPassword']);
$result = mysqli_query($conn,"SELECT * FROM `users` WHERE email='$email'");

$result = mysqli_fetch_array($result);

if($result["email"] == $email) {
    mysqli_query($conn,"UPDATE users set password='$generatedPassword' WHERE email='$email'");
    echo "New password has been sent to your email.";

    $email_from = 'SGTestingInstitute';
    $email_subject = "Your Password Has Been Reset";

    $message = '<html><body>';
    $message .= '<p>Your password has been reset successfully.</p>';
    $message .= '<div style="margin: 15px;"><strong>Username: </strong> '. $email.'</div>';
    $message .= '<div style="margin: 15px;"><strong>Password: </strong>' . $_POST['generatedPassword'] . '</div>';
    $message .= '<p style="margin-top: 25px;">You can change the autogenerated password once you login.</p>';
    $message .= "</body></html>";

    $to = $email;
    $headers = "From: $email_from \r\n";
    $headers .= "MIME-Version: 1.0\r\n";
    $headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";
    mail($to,$email_subject,$message,$headers);

} else {
    echo "Email does not exist in our database.";
}


?>